MayaCalender: MayaCalender.o
	gcc -std=c99 -g MayaCalender.o -o MayaCalender
MayaCalender.o: MayaCalender.c
	gcc -c -std=c99 -g MayaCalender.c -o MayaCalender.o -g

clean:
	rm MayaCalender MayaCalender.o
