Exponentiation: Exponentiation.o 
	gcc -std=c99 -g Exponentiation.o -o Exponentiation 
Exponentiation.o: Exponentiation.c
	gcc -c -std=c99 -g Exponentiation.c -o Exponentiation.o -g 

clean:
	rm Exponentiation Exponentiation.o
