FinancialManagement: FinancialManagement.o 
	gcc -std=c99 -g FinancialManagement.o -o FinancialManagement 
FinancialManagement.o: FinancialManagement.c
	gcc -c -std=c99 -g FinancialManagement.c -o FinancialManagement.o -g 

clean:
	rm FinancialManagement FinancialManagement.o
